const core=window.AnotacionesCore,math=window.AnotacionesMath,$=id=>document.getElementById(id);
const STATE_KEY='anotaciones:v2',LEGACY_STATE_KEY='anotaciones:v1',MODE_KEY='anotaciones:modo:v1',SYSTEM_VOICE_KEY='anotaciones:voz-sistema:v1',FONT_SCALE_KEY='anotaciones:tipografia:v1',card=$('card');
const SWIPE_THRESHOLD=50,DRAG_TOLERANCE=12,ANIMATION_MS=180,HOLD_MS=550;
let state,index=0,side='front',view='folders',mode=localStorage.getItem(MODE_KEY)==='text'?'text':'voice';
let voice=false,voiceSide='front',editing=false,pointer=null,hold=null,held=false,heldAction=null,folderHold=null,backgroundHold=null,scrubbing=null,scrubFrame=null,scrubSample=null;
let consentResolve=null,allowSystem=localStorage.getItem(SYSTEM_VOICE_KEY)==='allowed',persistTimer=null,undoOperation=null,toastTimer=null,transitioning=false,keyboardWasOpen=false,pendingDeleteFolderId=null,pendingImport=null;
let editingSeparatorId=null,separatorEditing=false,mathOpen=false,mathTarget=null,savedMathInsertion=null;
const storedFontScale=(()=>{try{return JSON.parse(localStorage.getItem(FONT_SCALE_KEY)||'null')}catch{return null}})();
const clampFontScale=value=>Math.max(.7,Math.min(1.8,Number(value)||1));
let fontScales=typeof storedFontScale==='number'?{front:clampFontScale(storedFontScale),back:clampFontScale(storedFontScale)}:{front:clampFontScale(storedFontScale?.front),back:clampFontScale(storedFontScale?.back)};

function folder(){return core.findFolder(state,state.carpetaActivaId)}
function deck(){return folder()}
function current(){return folder()?.tarjetas[index]}
function editorFor(target=side){return $(target==='separator'?'separatorText':target==='front'?'headerText':'answerText')}
function fieldFor(target=side){return target==='separator'?'nombre':target==='front'?'cabecera':'respuesta'}
function persist(){localStorage.setItem(STATE_KEY,JSON.stringify(state));return Promise.resolve()}
function schedulePersist(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>void persist(),120)}
function showToast(message,{undo=false}={}){const toast=$('toast');$('toastText').textContent=message;$('undo').hidden=!undo;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true;undoOperation=null},3000)}
function reducedMotion(){return window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true}
function waitForAnimation(){return new Promise(resolve=>setTimeout(resolve,reducedMotion()?0:ANIMATION_MS))}
function serializeMixedNode(node){
  if(node.nodeType===Node.TEXT_NODE)return node.nodeValue||'';if(node.nodeType!==Node.ELEMENT_NODE&&node.nodeType!==Node.DOCUMENT_FRAGMENT_NODE)return '';
  if(node.nodeType===Node.ELEMENT_NODE){if(node.classList.contains('math-token'))return math.formula(node.dataset.latex||'');if(node.tagName==='BR')return '\n'}
  let value=Array.from(node.childNodes).map(serializeMixedNode).join('');if(node.nodeType===Node.ELEMENT_NODE&&(node.tagName==='DIV'||node.tagName==='P')&&!value.endsWith('\n'))value+='\n';return value;
}
function mixedSource(editor){return serializeMixedNode(editor).replace(/\n$/,'')}
function appendText(container,value){String(value).split('\n').forEach((line,position)=>{if(position)container.append(document.createElement('br'));if(line)container.append(document.createTextNode(line))})}
function validLatex(latex){try{return !window.MathLive?.validateLatex||window.MathLive.validateLatex(latex).length===0}catch{return false}}
function renderMixed(editor,value,editable=false){
  editor.replaceChildren();for(const part of math.parse(value)){if(part.type==='text'){appendText(editor,part.value);continue}const token=document.createElement('button');token.type='button';token.className='math-token';token.contentEditable='false';token.dataset.latex=part.latex;token.dataset.start=String(part.start);token.dataset.end=String(part.end);if(validLatex(part.latex)){const rendered=document.createElement('math-span');rendered.textContent=part.latex;token.append(rendered)}else{token.classList.add('invalid');token.textContent=part.raw}editor.append(token)}
  editor.contentEditable=editable?'true':'false';editor.spellcheck=editable;
}
function syncEditors(){const c=current();if(!c)return;if(core.isSeparator(c))renderMixed($('separatorText'),c.nombre,separatorEditing);else{renderMixed($('headerText'),c.cabecera,editing&&side==='front');renderMixed($('answerText'),c.respuesta,editing&&side==='back')}}
function applyFontScale(){
  const frontScale=fontScales.front,backScale=fontScales.back,values={'--front-font-min':`${1.6*frontScale}rem`,'--front-font-fluid':`${7*frontScale}vw`,'--front-font-max':`${2.3*frontScale}rem`,'--answer-font-size':`${backScale}rem`,'--editor-font-min':`${1.35*frontScale}rem`,'--editor-font-fluid':`${6*frontScale}vw`,'--editor-font-max':`${2*frontScale}rem`,'--back-editor-font-min':`${1.05*backScale}rem`,'--back-editor-font-fluid':`${4.8*backScale}vw`,'--back-editor-font-max':`${1.4*backScale}rem`};
  Object.entries(values).forEach(([name,value])=>card.style.setProperty(name,value));const active=fontScales[side];$('fontDecrease').disabled=active<=.7;$('fontIncrease').disabled=active>=1.8;
}
function renderMode(){card.classList.toggle('text-mode',mode==='text');card.classList.toggle('editing',mode==='text'&&editing);applyFontScale()}
function selectMode(next){mode=next;localStorage.setItem(MODE_KEY,mode);renderMode()}
function renderCard(){
  const c=current();if(!c)return;const special=core.isSeparator(c);card.classList.toggle('separator-card',special);card.style.background=special?`rgb(${c.color.r} ${c.color.g} ${c.color.b})`:'';card.style.color=special?(core.colorLuminance(c.color)>.52?'#111827':'#fff'):'';
  if(special)$('separatorColor').style.background=`rgb(${c.color.r} ${c.color.g} ${c.color.b})`;syncEditors();
  $('separatorFace').classList.toggle('hidden',!special);$('front').classList.toggle('hidden',special||side!=='front');$('back').classList.toggle('hidden',special||side!=='back');$('listening').classList.add('hidden');renderMode();
  card.classList.toggle('separator-editing',special&&separatorEditing);
}
function renderFolders(){
  const list=$('folderList');list.replaceChildren();$('emptyFolders').hidden=state.carpetas.length>0;
  state.carpetas.forEach(item=>{
    const row=document.createElement('div');row.className='folder-row';row.dataset.folderId=item.id;
    const open=document.createElement('button');open.type='button';open.className='folder-open';open.textContent=item.nombre;open.setAttribute('aria-label',`Abrir ${item.nombre}. Mantén presionado para eliminar`);
    const imported=document.createElement('button');imported.type='button';imported.className='folder-import';imported.textContent='↓';imported.setAttribute('aria-label',`Importar tarjetas en ${item.nombre}`);
    const cancelHold=bindFolderHold(open,row,item);open.addEventListener('click',()=>{cancelHold();if(open.dataset.suppressClick){delete open.dataset.suppressClick;return}openFolder(item.id)});imported.addEventListener('click',()=>void readClipboard(item,{source:'folder'}));
    row.append(open,imported);list.append(row);
  });
}
function renderView(){
  const active=folder();if(view==='deck'&&!active)view='folders';const deckVisible=view==='deck';$('deckView').hidden=!deckVisible;$('folderBack').hidden=false;$('folderBack').setAttribute('aria-label',deckVisible?'Elegir otra carpeta':'Salir de Anotaciones');$('foldersView').hidden=deckVisible;
  if(deckVisible)renderCard();else renderFolders();
}
function openFolder(id){const selected=core.findFolder(state,id);if(!selected)return;state.carpetaActivaId=id;index=0;side='front';editing=false;view='deck';void persist();renderView()}
function showFolders(){finishEditing();if(voice)void InScreen.module.vozCancelar();voice=false;view='folders';renderView()}
function leaveModule(){finishEditing();if(voice)void window.InScreen?.module?.vozCancelar?.();voice=false;const exit=window.InScreen?.module?.salir;if(typeof exit==='function')exit();else history.back()}
function bindFolderHold(button,row,item){
  const cancel=()=>{if(folderHold?.button===button){clearTimeout(folderHold.timer);folderHold=null}row.classList.remove('holding')};
  button.addEventListener('pointerdown',event=>{if(event.button!==0||event.isPrimary===false)return;if(folderHold){clearTimeout(folderHold.timer);folderHold.row?.classList.remove('holding')}const gesture={button,row,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,timer:null};folderHold=gesture;row.classList.add('holding');try{button.setPointerCapture?.(event.pointerId)}catch{}gesture.timer=setTimeout(()=>{if(folderHold!==gesture)return;button.dataset.suppressClick='true';cancel();askDeleteFolder(item)},HOLD_MS)});
  button.addEventListener('pointermove',event=>{if(folderHold?.button===button&&folderHold.pointerId===event.pointerId&&Math.hypot(event.clientX-folderHold.startX,event.clientY-folderHold.startY)>DRAG_TOLERANCE)cancel()});
  button.addEventListener('pointerup',event=>{if(folderHold?.pointerId===event.pointerId)cancel()});button.addEventListener('pointercancel',cancel);button.addEventListener('pointerleave',cancel);button.addEventListener('lostpointercapture',cancel);button.addEventListener('contextmenu',event=>event.preventDefault());return cancel;
}
function openFolderDialog(){$('folderError').hidden=true;$('folderName').value='';$('folderDialog').hidden=false;setTimeout(()=>$('folderName').focus(),0)}
function closeFolderDialog(){$('folderDialog').hidden=true;$('folderName').blur()}
function askDeleteFolder(item){pendingDeleteFolderId=item.id;const count=core.navigableIndices(item).length;$('deleteFolderText').textContent=`¿Eliminar “${item.nombre}” y sus ${count} tarjeta${count===1?'':'s'}?`;$('deleteFolderDialog').hidden=false}
function closeDeleteFolder(){$('deleteFolderDialog').hidden=true;pendingDeleteFolderId=null;document.querySelectorAll('.folder-open').forEach(button=>delete button.dataset.suppressClick)}
async function readClipboard(targetFolder,{position=null,source='folder'}={}){
  let result;try{result=await window.InScreen?.module?.portapapeles?.()}catch{result={ok:false,error:'clipboard_read_failed'}}
  if(!result?.ok){showToast('No se pudo leer el portapapeles');return}const cards=core.parseClipboard(result.texto);if(!cards.length){showToast('No hay tarjetas admisibles para importar');return}
  pendingImport={folderId:targetFolder.id,cards};$('importSummary').textContent=`Se añadirán ${cards.length} tarjeta${cards.length===1?'':'s'} a “${targetFolder.nombre}”.`;
  Object.assign(pendingImport,{position,source});if(source==='deck')$('importSummary').textContent=`Se añadirán ${cards.length} tarjeta${cards.length===1?'':'s'} después de la tarjeta actual.`;
  const preview=$('importPreview');preview.replaceChildren();cards.slice(0,5).forEach(item=>{const entry=document.createElement('div');entry.className='preview-card';const header=document.createElement('strong');header.textContent=item.cabecera;const answer=document.createElement('span');answer.textContent=item.respuesta||'Sin respuesta';entry.append(header,answer);preview.append(entry)});
  if(cards.length>5){const more=document.createElement('p');more.textContent=`…y ${cards.length-5} más`;preview.append(more)}$('importDialog').hidden=false;
}
function closeImport(){$('importDialog').hidden=true;pendingImport=null}
function closeCardMenu(){$('cardMenu').hidden=true}
function openCardMenu(){finishEditing();$('cardMenu').hidden=false}
function updateSeparatorPreview(){const color=core.normalizeColor({r:$('separatorRed').value,g:$('separatorGreen').value,b:$('separatorBlue').value});for(const channel of ['Red','Green','Blue'])$(`separator${channel}Value`).value=$(`separator${channel}`).value;$('separatorPreview').style.background=`rgb(${color.r} ${color.g} ${color.b})`}
function openSeparatorColor(item=current()){if(!core.isSeparator(item))return;editingSeparatorId=item.id;$('separatorRed').value=item.color.r;$('separatorGreen').value=item.color.g;$('separatorBlue').value=item.color.b;updateSeparatorPreview();$('separatorDialog').hidden=false}
function closeSeparatorColor(){$('separatorDialog').hidden=true;editingSeparatorId=null}
function placeCaretAtEnd(editor){const range=document.createRange();range.selectNodeContents(editor);range.collapse(false);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);rememberMathInsertion()}
function beginSeparatorEditing(){const item=current();if(!core.isSeparator(item))return;separatorEditing=true;keyboardWasOpen=false;renderCard();const editor=$('separatorText');editor.focus({preventScroll:true});placeCaretAtEnd(editor);requestAnimationFrame(()=>editor.scrollIntoView({block:'center',behavior:'smooth'}))}
async function createSeparator(){closeCardMenu();finishEditing();const inserted=core.insertSeparator(deck(),index+1);if(inserted<0)return;index=inserted;side='front';await persist();renderCard();beginSeparatorEditing()}
function commitEditor(target=core.isSeparator(current())?'separator':side){const c=current();if(!c)return;const editor=editorFor(target),field=fieldFor(target),value=core.clean(mixedSource(editor));c[field]=value;c.actualizada=Date.now();void persist()}
function finishEditing(){if(mathOpen)closeMath(false);if(separatorEditing){commitEditor('separator');separatorEditing=false;$('separatorText').blur();if(view==='deck')renderCard();return}if(!editing)return;commitEditor(side);editing=false;editorFor().blur();if(view==='deck')renderCard()}
function changeFontScale(delta){fontScales[side]=clampFontScale(Math.round((fontScales[side]+delta)*10)/10);localStorage.setItem(FONT_SCALE_KEY,JSON.stringify(fontScales));applyFontScale()}
function resetCardStyle(){card.style.transition='';card.style.transform='';card.style.opacity=''}
function setDeleteProgress(distance){const amount=Math.max(0,distance),maxHeight=card.clientHeight*.2,height=Math.min(amount,maxHeight),progress=maxHeight?height/maxHeight:0;card.classList.add('delete-dragging');card.classList.toggle('delete-armed',amount>SWIPE_THRESHOLD);card.style.setProperty('--delete-height',`${height}px`);card.style.setProperty('--delete-icon-opacity',String(Math.min(1,progress*1.8)));card.style.setProperty('--delete-icon-scale',String(.7+Math.min(1,progress)*.3));return amount>SWIPE_THRESHOLD}
function resetDeleteIndicator(animate=true){card.classList.remove('delete-dragging','delete-armed');card.style.setProperty('--delete-height','0px');card.style.setProperty('--delete-icon-opacity','0');card.style.setProperty('--delete-icon-scale','.7');if(!animate){card.style.removeProperty('--delete-height');card.style.removeProperty('--delete-icon-opacity');card.style.removeProperty('--delete-icon-scale')}}
function setRecordProgress(distance){const amount=Math.max(0,distance),maxHeight=card.clientHeight*.2,height=Math.min(amount,maxHeight),progress=maxHeight?height/maxHeight:0;card.classList.add('record-dragging');card.classList.toggle('record-armed',amount>SWIPE_THRESHOLD);card.style.setProperty('--record-height',`${height}px`);card.style.setProperty('--record-icon-opacity',String(Math.min(1,progress*1.8)));card.style.setProperty('--record-icon-scale',String(.7+Math.min(1,progress)*.3));return amount>SWIPE_THRESHOLD}
function resetRecordIndicator(animate=true){card.classList.remove('record-dragging','record-armed');card.style.setProperty('--record-height','0px');card.style.setProperty('--record-icon-opacity','0');card.style.setProperty('--record-icon-scale','.7');if(!animate){card.style.removeProperty('--record-height');card.style.removeProperty('--record-icon-opacity');card.style.removeProperty('--record-icon-scale')}}
function springBack(){card.style.transition=reducedMotion()?'none':`transform ${ANIMATION_MS}ms ease, opacity ${ANIMATION_MS}ms ease`;card.style.transform='translate(0,0) rotate(0deg)';card.style.opacity='1';setTimeout(resetCardStyle,reducedMotion()?0:ANIMATION_MS)}
async function transitionCard(exitX,mutate){if(transitioning)return;transitioning=true;try{const rotation=Math.sign(exitX)*7;card.style.transition=reducedMotion()?'none':`transform ${ANIMATION_MS}ms ease, opacity ${ANIMATION_MS}ms ease`;card.style.transform=`translate(${exitX}px,0) rotate(${rotation}deg)`;card.style.opacity='0';await waitForAnimation();await mutate();renderCard();const sign=-Math.sign(exitX);card.style.transition='none';card.style.transform=`translate(${sign*(window.innerWidth+80)}px,0) rotate(${sign*7}deg)`;card.style.opacity='0';void card.offsetWidth;card.style.transition=reducedMotion()?'none':`transform ${ANIMATION_MS}ms ease, opacity ${ANIMATION_MS}ms ease`;card.style.transform='translate(0,0)';card.style.opacity='1';await waitForAnimation()}finally{resetCardStyle();transitioning=false}}
async function startVoice(target=side){if(voice)return;const status=await InScreen.module.vozEstado();let system=false;if(!status?.onDevice){if(!status?.servicioSistema)return;if(!allowSystem){$('consent').hidden=false;const ok=await new Promise(resolve=>consentResolve=resolve);if(!ok)return}system=true}voice=true;voiceSide=target;$('front').classList.add('hidden');$('back').classList.add('hidden');$('listening').classList.remove('hidden');$('transcript').textContent='Escuchando…';const result=await InScreen.module.vozIniciar({permitirServicioSistema:system});if(!result?.ok){voice=false;renderCard()}}
function beginEditing(){if(core.isSeparator(current())){beginSeparatorEditing();return}if(mode!=='text'||voice)return;editing=true;keyboardWasOpen=false;renderCard();const editor=editorFor();editor.focus({preventScroll:true});placeCaretAtEnd(editor);requestAnimationFrame(()=>editor.scrollIntoView({block:'center',behavior:'smooth'}))}
function tap(){if(voice||core.isSeparator(current()))return;if(editing)finishEditing();side=side==='front'?'back':'front';renderCard()}
async function changeCard(direction){finishEditing();if(direction<0)index--;else index=core.advance(deck(),index);side='front';await persist()}
async function navigate(direction,exitSign){if(voice||transitioning)return;if(direction<0&&index===0){springBack();return}if(direction>0&&!core.canAdvance(deck(),index)){springBack();showToast('No hay más tarjetas por ahora');return}await transitionCard(exitSign*(window.innerWidth+80),()=>changeCard(direction))}
async function removeCurrent(){if(voice||transitioning)return;transitioning=true;try{finishEditing();resetDeleteIndicator(false);resetRecordIndicator(false);undoOperation=core.removeUndoable(deck(),index);index=undoOperation.index;side='front';editing=false;await persist();renderCard();showToast('Tarjeta eliminada',{undo:true})}finally{transitioning=false}}
async function undoRemove(){if(!undoOperation||transitioning)return;clearTimeout(toastTimer);$('toast').hidden=true;index=core.restoreRemoved(deck(),undoOperation);undoOperation=null;side='front';editing=false;await persist();renderCard()}
function interactiveTarget(target){return Boolean(target.closest('button,textarea,[contenteditable="true"]'))}
function editedTarget(){return core.isSeparator(current())?'separator':side}
function rememberMathInsertion(){
  if(mathOpen)return;const target=editedTarget(),editor=editorFor(target),selection=getSelection();if(!selection?.rangeCount)return;const range=selection.getRangeAt(0);if(!editor.contains(range.endContainer))return;
  const before=document.createRange();before.selectNodeContents(editor);before.setEnd(range.endContainer,range.endOffset);savedMathInsertion={target,offset:serializeMixedNode(before.cloneContents()).length};
}
function setCaretAtSourceOffset(editor,offset){
  const wanted=Math.max(0,Number(offset)||0),range=document.createRange();let position=0,placed=false;
  for(const node of editor.childNodes){const value=serializeMixedNode(node),next=position+value.length;if(wanted<=next){if(node.nodeType===Node.TEXT_NODE){range.setStart(node,Math.max(0,Math.min(wanted-position,node.nodeValue?.length||0)))}else if(wanted<=position)range.setStartBefore(node);else range.setStartAfter(node);placed=true;break}position=next}
  if(!placed)range.selectNodeContents(editor),range.collapse(false);else range.collapse(true);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);savedMathInsertion={target:editedTarget(),offset:wanted};
}
function setCurrentSource(target,value){const item=current();if(!item)return;item[fieldFor(target)]=value;item.actualizada=Date.now();schedulePersist()}
function hideMathKeyboard(){try{window.mathVirtualKeyboard.hide({animate:true})}catch{}}
function closeMath(restoreFocus=true){if(!mathOpen)return;keyboardWasOpen=false;mathOpen=false;hideMathKeyboard();$('mathPanel').hidden=true;card.classList.remove('math-open');$('mathToggle').classList.remove('active');const target=mathTarget?.target,offset=mathTarget?.restoreOffset;mathTarget=null;if(restoreFocus&&target){const editor=editorFor(target);editor.focus({preventScroll:true});setCaretAtSourceOffset(editor,offset)}}
function openMath(targetInfo=null){
  if(mathOpen){confirmMath();return}const target=targetInfo?.target||editedTarget(),editor=editorFor(target),source=mixedSource(editor),fallback=savedMathInsertion?.target===target?savedMathInsertion.offset:source.length,offset=Math.max(0,Math.min(targetInfo?.start??fallback,source.length));
  mathTarget={target,start:targetInfo?.start??offset,end:targetInfo?.end??offset,restoreOffset:targetInfo?.end??offset};mathOpen=true;editor.blur();$('mathPanel').hidden=false;card.classList.add('math-open');$('mathToggle').classList.add('active');const field=$('mathField');field.value=targetInfo?.latex||'';field.focus({preventScroll:true});requestAnimationFrame(()=>{if(!mathOpen)return;try{window.mathVirtualKeyboard.layouts=['numeric','symbols','greek'];window.mathVirtualKeyboard.show({animate:true})}catch(error){console.warn('No se pudo abrir el teclado matemático',error)}});
}
function confirmMath(){
  if(!mathOpen||!mathTarget)return;const target=mathTarget.target,editor=editorFor(target),source=mixedSource(editor),latex=String($('mathField').value||'').trim();if(!latex){closeMath(true);return}const result=mathTarget.start===mathTarget.end?math.insert(source,mathTarget.end,latex):math.replace(source,mathTarget.start,mathTarget.end,latex);setCurrentSource(target,result.value);void persist();renderMixed(editor,result.value,true);mathTarget.restoreOffset=result.end;closeMath(false);editor.focus({preventScroll:true});keyboardWasOpen=false;setCaretAtSourceOffset(editor,result.end);
}
function editMathToken(event){
  const token=event.target.closest('.math-token');if(!token)return;event.preventDefault();event.stopPropagation();const editor=token.closest('.mixed-editor'),target=editor.id==='separatorText'?'separator':editor.id==='headerText'?'front':'back',before=document.createRange();before.selectNodeContents(editor);before.setEndBefore(token);const start=serializeMixedNode(before.cloneContents()).length,latex=token.dataset.latex||'',end=start+math.formula(latex).length;if(target==='separator'){if(!separatorEditing)beginSeparatorEditing()}else{side=target;if(!editing){selectMode('text');editing=true;renderCard()}}openMath({target,start,end,latex});
}

document.addEventListener('selectionchange',rememberMathInsertion);
for(const editor of document.querySelectorAll('.mixed-editor')){editor.addEventListener('click',editMathToken);editor.addEventListener('input',()=>{if(!editing&&!separatorEditing)return;setCurrentSource(editedTarget(),mixedSource(editor));rememberMathInsertion()});editor.addEventListener('keydown',event=>event.stopPropagation())}
$('mathToggle').addEventListener('pointerdown',event=>event.preventDefault());$('mathToggle').onclick=()=>openMath();

card.addEventListener('pointerdown',e=>{if(interactiveTarget(e.target)||voice||transitioning)return;pointer={x:e.clientX,y:e.clientY,id:e.pointerId,axis:null,deleteArmed:false,recordArmed:false};held=false;heldAction=null;try{card.setPointerCapture?.(e.pointerId)}catch{}hold=setTimeout(()=>{held=true;heldAction='edit'},HOLD_MS)});
card.addEventListener('pointermove',e=>{if(!pointer||held)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>DRAG_TOLERANCE){clearTimeout(hold);if(!pointer.axis){if(Math.abs(dx)>Math.abs(dy)*1.15)pointer.axis='horizontal';else if(Math.abs(dy)>Math.abs(dx)*1.15)pointer.axis='vertical'}}if(pointer.axis==='horizontal'){resetDeleteIndicator(false);resetRecordIndicator(false);card.style.transition='none';card.style.transform=`translate(${dx}px,0) rotate(${dx/35}deg)`;card.style.opacity=String(Math.max(.68,1-Math.abs(dx)/(window.innerWidth*1.8)))}else if(pointer.axis==='vertical'){resetCardStyle();if(dy<0){resetRecordIndicator(false);pointer.recordArmed=false;pointer.deleteArmed=setDeleteProgress(-dy)}else{resetDeleteIndicator(false);pointer.deleteArmed=false;pointer.recordArmed=setRecordProgress(dy)}}});
card.addEventListener('pointerup',e=>{if(!pointer){held=false;return}clearTimeout(hold);const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,axis=pointer.axis,deleteArmed=pointer.deleteArmed,recordArmed=pointer.recordArmed;pointer=null;if(held){held=false;heldAction=null;if(!core.isSeparator(current()))selectMode('text');beginEditing();return}if(axis==='vertical'){if(deleteArmed&&dy<0){void removeCurrent();return}if(recordArmed&&dy>0&&!core.isSeparator(current())){finishEditing();resetDeleteIndicator(false);resetRecordIndicator(false);selectMode('voice');void startVoice(side);return}resetDeleteIndicator(true);resetRecordIndicator(true);return}const swipe=axis==='horizontal'?core.classifySwipe(dx,0,SWIPE_THRESHOLD):null;if(swipe==='left'||swipe==='right'){void navigate(swipe==='left'?1:-1,swipe==='left'?-1:1);return}if(Math.hypot(dx,dy)<DRAG_TOLERANCE){resetCardStyle();tap();return}springBack()});
card.addEventListener('pointercancel',()=>{clearTimeout(hold);pointer=null;held=false;heldAction=null;resetDeleteIndicator(true);resetRecordIndicator(true);springBack()});card.addEventListener('contextmenu',e=>{if(!editing)e.preventDefault()});

function cancelBackgroundHold(){if(!backgroundHold)return;clearTimeout(backgroundHold.timer);backgroundHold=null}
document.addEventListener('pointerdown',event=>{if(view!=='deck'||voice||transitioning||event.button!==0||event.isPrimary===false||event.target!==document.body||event.clientY>=card.getBoundingClientRect().top)return;cancelBackgroundHold();const gesture={pointerId:event.pointerId,x:event.clientX,y:event.clientY,timer:null};backgroundHold=gesture;gesture.timer=setTimeout(()=>{if(backgroundHold!==gesture)return;backgroundHold=null;openCardMenu()},HOLD_MS)});
document.addEventListener('pointermove',event=>{if(backgroundHold?.pointerId===event.pointerId&&Math.hypot(event.clientX-backgroundHold.x,event.clientY-backgroundHold.y)>DRAG_TOLERANCE)cancelBackgroundHold()});
document.addEventListener('pointerup',event=>{if(backgroundHold?.pointerId===event.pointerId)cancelBackgroundHold()});document.addEventListener('pointercancel',cancelBackgroundHold);document.body.addEventListener('contextmenu',event=>{if(view==='deck'&&event.target===document.body&&event.clientY<card.getBoundingClientRect().top)event.preventDefault()});
document.addEventListener('click',event=>{if(view==='deck'&&(editing||separatorEditing)&&!event.target.closest('#card,.overlay,.icon-button'))finishEditing()});

function hideScrubBubble(){$('scrubBubble').hidden=true}
function renderScrub(clientX){const indices=core.navigableIndices(folder());if(!indices.length)return;const rect=$('scrubber').getBoundingClientRect(),position=core.scrubPosition(clientX,rect.left,rect.width,indices.length),nextIndex=indices[position];if(nextIndex!==index){index=nextIndex;side='front';editing=false;renderCard()}const bubble=$('scrubBubble');$('scrubBubbleText').textContent=String(position+1);bubble.style.left=`${Math.max(34,Math.min(window.innerWidth-34,clientX))}px`;bubble.style.top=`${rect.top}px`;bubble.hidden=false}
function flushScrub(){if(scrubFrame!==null){cancelAnimationFrame(scrubFrame);scrubFrame=null}const sample=scrubSample;scrubSample=null;if(sample)renderScrub(sample.x)}
function queueScrub(event){scrubSample={x:event.clientX};if(scrubFrame!==null)return;scrubFrame=requestAnimationFrame(()=>{scrubFrame=null;const sample=scrubSample;scrubSample=null;if(sample)renderScrub(sample.x)})}
function cancelScrubFrame(){if(scrubFrame!==null)cancelAnimationFrame(scrubFrame);scrubFrame=null;scrubSample=null}
$('scrubber').addEventListener('pointerdown',event=>{if(voice||view!=='deck'||!core.navigableIndices(folder()).length)return;scrubbing={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,startIndex:index,active:false};try{$('scrubber').setPointerCapture?.(event.pointerId)}catch{}});
$('scrubber').addEventListener('pointermove',event=>{if(!scrubbing||scrubbing.pointerId!==event.pointerId)return;const dx=event.clientX-scrubbing.startX,dy=event.clientY-scrubbing.startY;if(!scrubbing.active){if(Math.abs(dx)<=DRAG_TOLERANCE||Math.abs(dx)<=Math.abs(dy)*1.15)return;scrubbing.active=true;finishEditing()}queueScrub(event)});const endScrub=event=>{if(!scrubbing||(event.pointerId!==undefined&&scrubbing.pointerId!==event.pointerId))return;if(scrubbing.active)flushScrub();else cancelScrubFrame();scrubbing=null;hideScrubBubble()};$('scrubber').addEventListener('pointerup',endScrub);$('scrubber').addEventListener('pointercancel',event=>{if(!scrubbing||scrubbing.pointerId!==event.pointerId)return;const restore=scrubbing.active?scrubbing.startIndex:null;scrubbing=null;cancelScrubFrame();hideScrubBubble();if(restore!==null&&index!==restore){index=restore;side='front';editing=false;renderCard()}});

$('folderBack').onclick=()=>view==='deck'?showFolders():leaveModule();$('addFolder').onclick=openFolderDialog;$('cancelFolder').onclick=closeFolderDialog;
$('folderForm').addEventListener('submit',event=>{event.preventDefault();const name=$('folderName').value;if(!core.folderName(name)){$('folderError').textContent='Escribe un nombre para la carpeta.';$('folderError').hidden=false;return}const created=core.createFolder(state,name);if(!created){$('folderError').textContent='Ya existe una carpeta con ese nombre.';$('folderError').hidden=false;return}closeFolderDialog();void persist();renderFolders();showToast('Carpeta creada')});
$('cancelDeleteFolder').onclick=closeDeleteFolder;$('confirmDeleteFolder').onclick=()=>{const removed=core.removeFolder(state,pendingDeleteFolderId);closeDeleteFolder();void persist();renderFolders();if(removed)showToast('Carpeta eliminada')};
$('cancelImport').onclick=closeImport;$('confirmImport').onclick=()=>{if(!pendingImport)return;const operation=pendingImport,target=core.findFolder(state,operation.folderId),requested=Number.isInteger(operation.position)?operation.position:null,fallback=core.isBlank(target?.tarjetas?.at(-1))?target.tarjetas.length-1:target?.tarjetas?.length||0,insertAt=requested===null?fallback:Math.max(0,Math.min(requested,fallback)),count=core.insertCards(target,operation.cards,insertAt);closeImport();if(operation.source==='deck'&&count){index=insertAt;side='front';editing=false;void persist();renderCard()}else{void persist();renderFolders()}showToast(`${count} tarjeta${count===1?'':'s'} importada${count===1?'':'s'}`)};
$('cancelCardMenu').onclick=closeCardMenu;$('addSeparator').onclick=()=>void createSeparator();$('addClipboard').onclick=()=>{closeCardMenu();void readClipboard(deck(),{position:index+1,source:'deck'})};
$('separatorColor').onclick=()=>openSeparatorColor();$('cancelSeparator').onclick=closeSeparatorColor;$('separatorForm').addEventListener('submit',event=>{event.preventDefault();const item=deck()?.tarjetas.find(card=>card.id===editingSeparatorId);if(!item)return closeSeparatorColor();item.color=core.safeColor({r:$('separatorRed').value,g:$('separatorGreen').value,b:$('separatorBlue').value});item.actualizada=Date.now();closeSeparatorColor();void persist();renderCard()});
for(const id of ['separatorRed','separatorGreen','separatorBlue'])$(id).addEventListener('input',updateSeparatorPreview);
$('fontControls').addEventListener('pointerdown',e=>e.preventDefault());$('fontDecrease').onclick=()=>changeFontScale(-.1);$('fontIncrease').onclick=()=>changeFontScale(.1);$('stop').onclick=()=>{if(voice)void InScreen.module.vozDetener()};$('listening').addEventListener('click',e=>{if(!e.target.closest('#stop')&&voice)void InScreen.module.vozDetener()});$('undo').onclick=()=>void undoRemove();
$('deny').onclick=()=>{$('consent').hidden=true;consentResolve?.(false);consentResolve=null};$('allow').onclick=()=>{allowSystem=true;localStorage.setItem(SYSTEM_VOICE_KEY,'allowed');$('consent').hidden=true;consentResolve?.(true);consentResolve=null};
function updateViewport(){const viewport=window.visualViewport,height=Math.round(viewport?.height||window.innerHeight),keyboard=Boolean(viewport&&window.innerHeight-height>120),active=document.activeElement?.classList?.contains('mixed-editor')?document.activeElement:null;document.documentElement.style.setProperty('--viewport-height',`${height}px`);document.body.classList.toggle('keyboard-open',keyboard);if(keyboard&&active)requestAnimationFrame(()=>active.scrollIntoView({block:'center'}));if(!mathOpen&&keyboardWasOpen&&!keyboard&&(editing||separatorEditing)){finishEditing();active?.blur()}keyboardWasOpen=keyboard}
window.visualViewport?.addEventListener('resize',updateViewport);window.visualViewport?.addEventListener('scroll',updateViewport);window.addEventListener('resize',updateViewport);updateViewport();
window.addEventListener('inscreen:atras',event=>{if(!mathOpen)return;event.preventDefault();closeMath(true)});
window.addEventListener('inscreen:voz',async e=>{if(!voice)return;const d=e.detail||{};if(d.estado==='parcial')$('transcript').textContent=d.texto||'Escuchando…';if(d.estado==='error'){voice=false;renderCard()}if(d.estado==='final'){voice=false;const text=core.clean(d.texto);if(text){current()[fieldFor(voiceSide)]=text;current().actualizada=Date.now();await persist()}side=voiceSide;renderCard()}});
(async()=>{if(window.MathfieldElement){window.MathfieldElement.fontsDirectory='./vendor/mathlive/fonts';window.MathfieldElement.soundsDirectory=null}let saved=null;try{saved=JSON.parse(localStorage.getItem(STATE_KEY)||'null');if(!saved)saved=JSON.parse(localStorage.getItem(LEGACY_STATE_KEY)||'null')}catch{}state=core.normalize(saved);view=folder()?'deck':'folders';index=0;await persist();renderView()})().catch(error=>{document.body.textContent=error.message});
