const core=window.AnotacionesCore,$=id=>document.getElementById(id);let state,index=0,side='front',voice=false,voiceSide='front',pointer=null,hold=null,consentResolve=null,allowSystem=false;
const card=$('card');
function current(){return state.tarjetas[index]}
function render(){const c=current();$('position').textContent=`${index+1} de ${state.tarjetas.length}`;$('headerText').textContent=c.cabecera;$('answerText').textContent=c.respuesta;$('frontHint').textContent=c.cabecera?'':'Tocá para dictar la cabecera';$('backHint').textContent='';$('front').classList.toggle('hidden',side!=='front');$('back').classList.toggle('hidden',side!=='back');$('listening').classList.add('hidden');$('previous').disabled=index===0;}
function persist(){localStorage.setItem('anotaciones:v1',JSON.stringify(state));return Promise.resolve()}
function toast(){const view=$('toast');view.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>view.hidden=true,2400)}
async function startVoice(target=side){if(voice)return;const status=await InScreen.module.vozEstado();let system=false;if(!status?.onDevice){if(!status?.servicioSistema)return;if(!allowSystem){$('consent').hidden=false;const ok=await new Promise(r=>consentResolve=r);if(!ok)return;}system=true;}voice=true;voiceSide=target;$('front').classList.add('hidden');$('back').classList.add('hidden');$('listening').classList.remove('hidden');$('transcript').textContent='Escuchando…';const result=await InScreen.module.vozIniciar({permitirServicioSistema:system});if(!result?.ok){voice=false;render();}}
function tap(){const c=current();if(side==='front'&&!c.cabecera)return void startVoice('front');if(side==='front'){side='back';render();return}if(!c.respuesta)return void startVoice('back');side='front';render()}
async function move(direction){if(voice)return;if(direction<0){if(index===0)return;index--;side='front';render();return}if(!core.canAdvance(state,index)){toast();return}index=core.advance(state,index);side='front';await persist();render()}
function openMenu(){if(voice)return;$('menu').hidden=false}
function closeMenu(){$('menu').hidden=true}
card.addEventListener('pointerdown',e=>{pointer=e.clientX;hold=setTimeout(openMenu,550)});card.addEventListener('pointermove',e=>{if(pointer!==null&&Math.abs(e.clientX-pointer)>12)clearTimeout(hold)});card.addEventListener('pointerup',e=>{clearTimeout(hold);const delta=e.clientX-pointer;pointer=null;if($('menu').hidden===false)return;if(Math.abs(delta)>50)void move(delta<0?1:-1);else tap()});card.addEventListener('pointercancel',()=>{clearTimeout(hold);pointer=null});
$('previous').onclick=()=>void move(-1);$('next').onclick=()=>void move(1);$('stop').onclick=()=>void InScreen.module.vozDetener();$('cancelMenu').onclick=closeMenu;
$('edit').onclick=()=>{closeMenu();$('editor').value=side==='front'?current().cabecera:current().respuesta;$('editorOverlay').hidden=false;$('editor').focus()};$('cancelEdit').onclick=()=>$('editorOverlay').hidden=true;$('saveEdit').onclick=async()=>{const value=core.clean($('editor').value);if(side==='front')current().cabecera=value;else current().respuesta=value;current().actualizada=Date.now();$('editorOverlay').hidden=true;await persist();render()};
$('rerecord').onclick=()=>{closeMenu();void startVoice(side)};$('remove').onclick=async()=>{closeMenu();if(!confirm('¿Eliminar esta tarjeta?'))return;index=core.remove(state,index);side='front';await persist();render()};
$('deny').onclick=()=>{$('consent').hidden=true;consentResolve?.(false);consentResolve=null};$('allow').onclick=()=>{allowSystem=true;$('consent').hidden=true;consentResolve?.(true);consentResolve=null};
window.addEventListener('inscreen:voz',async e=>{if(!voice)return;const d=e.detail||{};if(d.estado==='parcial')$('transcript').textContent=d.texto||'Escuchando…';if(d.estado==='error'){voice=false;render()}if(d.estado==='final'){voice=false;const text=core.clean(d.texto);if(text){if(voiceSide==='front')current().cabecera=text;else current().respuesta=text;current().actualizada=Date.now();await persist()}side=voiceSide;render()}});
(async()=>{let saved=null;try{saved=JSON.parse(localStorage.getItem('anotaciones:v1')||'null')}catch{}state=core.normalize(saved);await persist();render()})().catch(error=>{document.body.textContent=error.message});
