const test=require('node:test'),assert=require('node:assert/strict'),core=require('../modules/anotaciones/core.js');

const folder=name=>{const state=core.normalize(null),created=core.createFolder(state,name);return {state,folder:created}};

test('new installations start without folders',()=>{const state=core.normalize(null);assert.equal(state.version,2);assert.deepEqual(state.carpetas,[]);assert.equal(state.carpetaActivaId,null)});
test('migrates the legacy deck into an active General folder',()=>{const state=core.normalize({version:1,tarjetas:[{id:'old',cabecera:'Uno',respuesta:'Respuesta',actualizada:1}]});assert.equal(state.carpetas.length,1);assert.equal(state.carpetas[0].nombre,'General');assert.equal(state.carpetaActivaId,state.carpetas[0].id);assert.deepEqual(state.carpetas[0].tarjetas.map(card=>card.cabecera),['Uno',''])});
test('normalization only keeps an existing active folder id',()=>{const initial=folder('Semana 1').state;initial.carpetaActivaId='missing';assert.equal(core.normalize(initial).carpetaActivaId,null)});
test('keeps line breaks in card text after saving and loading',()=>{const text='Primera línea\r\nSegunda línea\n\nTercera línea';const state=core.normalize({carpetas:[{id:'week',nombre:'Semana',tarjetas:[{id:'card',cabecera:'Tema',respuesta:text}]}],carpetaActivaId:'week'});assert.equal(state.carpetas[0].tarjetas[0].respuesta,'Primera línea\nSegunda línea\n\nTercera línea')});
test('creates unique trimmed folder names ignoring case',()=>{const {state}=folder('  Semana   1 ');assert.equal(state.carpetas[0].nombre,'Semana 1');assert.equal(core.createFolder(state,'semana 1'),null);assert.equal(core.createFolder(state,' '),null);assert.ok(core.createFolder(state,'Semana 2'))});
test('deleting the active folder clears its selection',()=>{const {state,folder:created}=folder('Semana');state.carpetaActivaId=created.id;assert.equal(core.removeFolder(state,created.id).nombre,'Semana');assert.equal(state.carpetaActivaId,null);assert.equal(state.carpetas.length,0)});
test('parses one card per non-empty line and splits only the first colon',()=>{const cards=core.parseClipboard(' Tema : Respuesta\nSolo cabecera\nURL:https://sitio:ruta\n\n:sin cabecera');assert.deepEqual(cards.map(({cabecera,respuesta,linea})=>({cabecera,respuesta,linea})),[{cabecera:'Tema',respuesta:'Respuesta',linea:1},{cabecera:'Solo cabecera',respuesta:'',linea:2},{cabecera:'URL',respuesta:'https://sitio:ruta',linea:3}])});
test('successive imports append in order before one trailing draft',()=>{const {folder:created}=folder('Semana');assert.equal(core.appendCards(created,[{cabecera:'Uno',respuesta:'1'},{cabecera:'Dos',respuesta:''}]),2);const draftId=created.tarjetas.at(-1).id;assert.equal(core.appendCards(created,[{cabecera:'Tres',respuesta:'3'}]),1);assert.deepEqual(created.tarjetas.map(card=>card.cabecera),['Uno','Dos','Tres','']);assert.equal(created.tarjetas.at(-1).id,draftId)});
test('inserts imported cards at a requested position in order',()=>{const {folder:created}=folder('Semana');core.appendCards(created,[{cabecera:'Uno'},{cabecera:'Cuatro'}]);assert.equal(core.insertCards(created,[{cabecera:'Dos'},{cabecera:'Tres'}],1),2);assert.deepEqual(created.tarjetas.map(card=>card.cabecera),['Uno','Dos','Tres','Cuatro',''])});
test('creates, normalizes and navigates unnamed separators',()=>{const {folder:created}=folder('Semana'),position=core.insertSeparator(created,0,{r:0,g:0,b:0});assert.equal(position,0);const item=created.tarjetas[0];assert.equal(item.tipo,'separador');assert.equal(item.nombre,'');assert.ok(core.colorLuminance(item.color)>=.24);assert.deepEqual(core.navigableIndices(created),[0]);const normalized=core.normalize({carpetas:[created],carpetaActivaId:created.id});assert.equal(normalized.carpetas[0].tarjetas[0].tipo,'separador')});
test('random separator colors stay away from dark and light extremes',()=>{for(let i=0;i<100;i++){const luminance=core.colorLuminance(core.randomColor());assert.ok(luminance>=.24&&luminance<=.79)}});
test('navigable indices exclude the trailing draft',()=>{const {folder:created}=folder('Semana');core.appendCards(created,[{cabecera:'Uno'},{cabecera:'Dos'}]);assert.deepEqual(core.navigableIndices(created),[0,1])});
test('maps scrubber extremes and intermediate positions',()=>{assert.equal(core.scrubPosition(-10,0,100,26),0);assert.equal(core.scrubPosition(100,0,100,26),25);assert.equal(core.scrubPosition(50,0,100,26),13);assert.equal(core.scrubPosition(10,0,100,1),0)});
test('advances only after a header and keeps a trailing blank',()=>{const {folder:created}=folder('Semana');assert.equal(core.advance(created,0),0);created.tarjetas[0].cabecera='Tema';assert.equal(core.advance(created,0),1);assert.equal(created.tarjetas.length,2)});
test('restores an undoable card removal at its original position',()=>{const {folder:created}=folder('Semana');core.appendCards(created,[{cabecera:'Uno'},{cabecera:'Dos'}]);const operation=core.removeUndoable(created,1);assert.deepEqual(created.tarjetas.map(card=>card.cabecera),['Uno','']);assert.equal(core.restoreRemoved(created,operation),1);assert.deepEqual(created.tarjetas.map(card=>card.cabecera),['Uno','Dos',''])});
test('classifies dominant card swipes independently',()=>{assert.equal(core.classifySwipe(-51,0),'left');assert.equal(core.classifySwipe(51,0),'right');assert.equal(core.classifySwipe(0,-51),'up');assert.equal(core.classifySwipe(60,60),null)});
